# Generated by Django 5.1.3 on 2024-11-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenDescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('imagen1', models.ImageField(upload_to='imagenes/', verbose_name='Imagen 1')),
                ('imagen2', models.ImageField(upload_to='imagenes/', verbose_name='Imagen 2')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
