# Generated by Django 5.1.3 on 2024-11-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagendescripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagendescripcion',
            name='titulo',
            field=models.CharField(default='Evento', max_length=100, verbose_name='Título del Evento'),
        ),
        migrations.AlterField(
            model_name='imagendescripcion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='imagendescripcion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='imagendescripcion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen 2'),
        ),
        migrations.DeleteModel(
            name='Observador',
        ),
    ]
