# Generated by Django 5.1.3 on 2024-11-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imagendescripcion_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagendescripcion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagendescripcion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagendescripcion',
            name='imagen1',
            field=models.ImageField(upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagendescripcion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagendescripcion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
