# Generated by Django 5.1.3 on 2024-11-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_imagendescripcion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='estudiante_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
