# Generated by Django 5.1.3 on 2024-11-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_observacion_estudiante_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='acudiente',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grupo_sanguineo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='grado',
            name='descripcion',
        ),
    ]
